### ISSUE TITLE
FFT.Forward() consumes all my memory after 1 minute

### ISSUE THREAD

**Issue by janschneiderou** [ddf/Minim#26]
AudioSource x;
...
FFT f;
f = new FFT(x.bufferSize(), x.sampleRate());
f.window(FFT.HAMMING);
f.forward(x.mix);

I checked line by line and it seems that the f.forward has a memory leak.

**Comment by ddf** [comment]
I don't think it is the FFT causing this because as far as I can tell there are no memory allocations occuring during the forward method. If you are making a new FFT object every time you make a call to forward, that is more likely the cause of your memory leak. You only need to make one FFT object and you can call forward on it every frame to update the spectrum.
