### ISSUE TITLE
Neither Balance nor Pan available for mono AudioPlayer on Linux?

### ISSUE THREAD

**Issue by markstock** [ddf/Minim#44]
Processing 3.0b5 (linux64), and am just now trying Minim (2.2.0) because of a myriad of critical problems with the default processing.sound library. I was hoping to be able to pan my mono .wav files, but apparently neither pan nor balance are supported on my Fedora 21 machine with java-1.8.0-openjdk-1.8.0.51-4.b16.fc21.x86_64. Any idea what's wrong?

**Comment by ddf** [comment]
The pan and balance provided through the AudioPlayer class are pretty system dependent, which is something I intend to fix in the future. When constructing an AudioPlayer, Minim will request an output that matches the format of the file, so it is asking for a mono output, which probably doesn't have pan and balance because those are stereo operations. You might have better luck using a FilePlayer UGen and patching it through a Pan UGen to an stereo AudioOutput.

See:
https://github.com/ddf/Minim/blob/master/examples/Synthesis/filePlayerExample/filePlayerExample.pde

and

https://github.com/ddf/Minim/blob/master/examples/Synthesis/panExample/panExample.pde

**Comment by markstock** [comment]
Can I not request a stereo AudioPlayer and then load a mono .wav into it? I'm trying to understand the patching system in UGen, but am afraid to commit to using it for all of the sound files that I have for fear that I'll uncover some other problem (which is usually what happens when I find myself using Processing for non-toy problems). It might be simplest for me to just create 5 stereo versions of each mono sound clip, panned to a different position, and just load those in as separate AudioPlayer files.

**Comment by ddf** [comment]
Afraid not. It is not possible to load a new file into an existing AudioPlayer.

**Comment by ddf** [comment]
Confirmed, it seems to be the mono aspect of the file that causes this. If I ask for a mono AudioOutput I also wind up with no Pan or Balance controls. This doesn't surprise me, but it sucks that Linux is different in this way.

**Comment by markstock** [comment]
So if I make a stereo version of the mono file with the voice right in the middle, will Pan or Balance work properly (moving that sound between left and right)?

**Comment by ddf** [comment]
yes, I would expect it to wind up with at least one of those controls in that case.

**Comment by markstock** [comment]
Yes, Balance works for stereo files on Linux. Thank you for your help.
