### ISSUE TITLE
large audio files work on Windows not on Raspberry Pi

### ISSUE THREAD

**Issue by 12jonboy12** [ddf/Minim#65]
The program I was working on opens about 6 MP3 files using the minim library for processing.
When running on Windows the program works perfectly, running on the Raspberry Pi, however, it will only work if I limit the program to 2 or three audio tracks, or switch them out with smaller audio tracks. 
They are all the same MP3 format and exported from the same program at the same bitrate, I even tested using .wav and it had the same issue. 
And it doesn't seem to matter which of the files I use just as long as I don't force it to try and load all of them at the same time, the last files I try to open are always the ones that fail on the Raspberry Pi.
I get this error message but I am 99.9999% sure it has nothing to do with the format as all of the files play fine individually.

    ==== JavaSound Minim Error ====
    ==== Unable to return a SourceDataLine: unsupported format - PCM_SIGNED 44100.0 Hz, 16 bit, mono, 2 bytes/frame, little-endian

I have stripped down the code to the bare minimum to receive this error message.

    import ddf.minim.*;
    import ddf.minim.effects.*;
    Minim minim;
    AudioPlayer player1;
    AudioPlayer player2;
    AudioPlayer player3;
    AudioPlayer player4;
    AudioPlayer player5;
    void setup()
    {
      minim = new Minim(this);
      player1 = minim.loadFile("singer_control_track0_0.mp3", 2048);
      player2 = minim.loadFile("singer_control_track0_1.mp3", 2048);
      player3 = minim.loadFile("singer_control_track0_2.mp3", 2048);
      player4 = minim.loadFile("singer_control_track0_3.mp3", 2048);
      player5 = minim.loadFile("song0.mp3", 2048);
     }
    
    void draw()
    {
      background(0);
    }
    

It seems like it's using close to 512 megabytes of swap space.
I've increased the size of the swap file on raspbian, as well as increasing the maximum memory usage inside the processing settings.
I've tried using MP3 files at a drastically lower bitrate.
it does not look like my swap or ram are full.
Sorry if this turns out not to be a bug.
Thank you.
@gohai

**Comment by ddf** [comment]
It's not so much a bug as it is a limitation on some systems due to how AudioPlayer is implemented. Basically, what happens behind the scenes is that each AudioPlayer is requesting a direct connection to a low-level output line and some JavaSound implementations have a very limited number they can have open at once. You should be able to around this by loading each of your mp3 files into a FilePlayer (http://code.compartmental.net/minim/fileplayer_class_fileplayer.html) and then creating only one AudioOutput. You can play the files by passing your AudioOutput to the patch method of FilePlayer and then calling Play on the FilePlayer (their interface is the same as AudioPlayer). The example on the documentation page for FilePlayer in that link shows how.

Please let me know if that fixes the issue for you and I will close this issue.

**Comment by gohai** [comment]
Not OP but thanks a lot for this helpful answer, @ddf!

**Comment by 12jonboy12** [comment]
Thank you, you can close the issue, it doesn't exactly fix my issue as I was doing something strange (using muted sound files to control something else). but I overhauled my program to use a .csv file with time in milliseconds and made another program to make csv files out of my .mp3 files, still an odd way to do it, but it works ok and uses much less ram.
Thank you for your help.
